apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-enforce-expire.fullname" . }}
data:
  {{- if .Values.configMapProperties }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.configMapProperties "context" $ ) | nindent 2 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-enforce-expire.rulesConfigMap" . }}
data:
  rules.yaml: |
    {{- if .Values.configMapRules }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configMapRules "context" $ ) | nindent 4 }}
    {{- end }}
